#개발용 설정 설정
spring.application.name=OCR_CONVERTER
# 포트설정
server.port=8080
# 테스트 (구글 인증 TEST)
ocr.google-credentials-path=C:/Users/User/Downloads/lif-fv-cnvr-28e48cfee7e9.json
ocr.server-url=192.168.0.249
ocr.paddle-url=http://127.0.0.1:5999/paddleocr
ocr.result-dir=\\\\192.168.0.249\\Users\\User\\Documents\\test
ocr.image-dir=${ocr.result-dir}
ocr.output-pdf-path=${ocr.result-dir}\\ocr_results\\OCR_Result.pdf
ocr.ocr-result-dir=${ocr.result-dir}\\ocr_results
ocr.font-resource-path=fonts/NanumSquareR.ttf
ocr.status-dir=C:/workspace/OCR_CONVERTER/OCR_RESULTS
# 정적 리소스 설정
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**
# 세션 설정
server.servlet.session.timeout=86400s
# 파일업로드 제한 설정 (최대 500MB 파일, 총 100GB까지 허용 가능)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=100GB



## 운영용 설정 설정 (리눅스 설정)
## 애플리케이션 이름 설정
#spring.application.name=OCR_CONVERTER
#
## 포트설정
#server.port=8090
#
## OCR 관련 (구글 인증 설정)
#ocr.google-credentials-path=/mnt/AI_DATA/paddle/lif-fv-cnvr-28e48cfee7e9.json
#ocr.server-url=192.168.0.232:22
#ocr.paddle-url=http://192.168.0.232:5999/paddleocr
#ocr.result-dir=/mnt/AI_DATA/paddle/test
#ocr.image-dir=${ocr.result-dir}
#ocr.output-pdf-path=${ocr.result-dir}/ocr_results/OCR_Result.pdf
#ocr.ocr-result-dir=${ocr.result-dir}/ocr_results
#ocr.font-resource-path=fonts/NanumSquareR.ttf
#ocr.status-dir=/mnt/AI_DATA/paddle/status
#
## 정적 리소스 설정
#spring.web.resources.static-locations=classpath:/static/
#spring.mvc.static-path-pattern=/static/**
#
## 세션 설정
#server.servlet.session.timeout=3d
## /mnt/AI_DATA/tmp
#spring.servlet.multipart.location=/mnt/AI_DATA/paddle/tmp
#
## 파일업로드 제한 설정 (최대 500MB 파일, 총 200GB까지 허용 가능)
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=500MB
#spring.servlet.multipart.max-request-size=200GB
